# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoyoCoreFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoyoCoreFramework
  # Pods for RoyoCoreFramework
	pod 'SkeletonView'
  pod 'SwiftyJSON'
  pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'Alamofire'
  pod 'EZSwiftExtensions'
  pod 'NVActivityIndicatorView'
  pod 'ObjectMapper'
  pod 'FacebookCore'
  pod 'FacebookShare'
  pod 'FacebookLogin'
  pod 'ADCountryPicker', '~> 2.1.0'

end